import { Routes } from '@angular/router';
import { ListProduct } from './list-product/list-product';
import { ProductDetail } from './product-detail/product-detail';
import { NotFound } from './not-found/not-found';
import { Ex28 } from './ex28/ex28';
import { Ex27 } from './ex27/ex27';
import { Ex26 } from './ex26/ex26';
import { Books } from './books/books';
import { BookDetail } from './book-detail/book-detail';
import { BookNew } from './book-new/book-new';
import { BookUpdate } from './book-update/book-update';
import { BookDelete } from './book-delete/book-delete';
import { FileUpload } from './file-upload/file-upload';
import { FashionDetailComponent } from './fashion-detail/fashion-detail';
import { Login } from './login/login';
import { ShoppingCart } from './shopping-cart/shopping-cart';

export const routes: Routes = [
  { path: 'products', component: ListProduct },
  { path: 'sản-phẩm-1/:id', component: ProductDetail },
  { path: 'bitcoin', component: Ex28 },
  { path: 'ex27', component: Ex27 },
  { path: 'fake-products', component: Ex26 },
  { path: 'books', component: Books },
  { path: 'book-detail/:id', component: BookDetail },
  { path: 'book-detail', component: BookDetail },
  { path: 'book-new', component: BookNew },
  { path: 'book-update', component: BookUpdate },
  { path: 'book-delete', component: BookDelete },
  { path: 'file-upload', component: FileUpload },
  { path: 'fashion', component: FashionDetailComponent },
  { path: 'login', component: Login },
  { path: 'shopping-cart', component: ShoppingCart },
  { path: '**', component: NotFound }
];
